'use client';

import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { useLanguage } from '../context/LanguageContext';
import Grainient from './Grainient';
import './MugranStudio.css';
import './MugranStudioRefine.css';
import './MugranStudioPro.css';
import './MugranStudioContrast.css';
import './MugranPolish.css';
import './GrainientHero.css';
import './MugranServiceIndex.css';
import './MugranHeroMedia.css';
import './MugranHeroFix.css';
import './MugranHeroFilmControl.css';
import './MugranInnerPages.css';
import './MugranApproach.css';
import './MugranApproachFix.css';
import './MugranPerceptionGap.css';
import './MugranServicesPage.css';

if (typeof window !== 'undefined') gsap.registerPlugin(ScrollTrigger);

const copy = {
  ar: {
    home: { hero: 'نجعل صورة الشركة\nتواكب حقيقتها.', lead: 'مُقرن شركة إبداعية مستقلة تبني العلامة، وتصمم التجربة الرقمية، وتحولها إلى حضور مؤثر في السوق.', gap: 'قد تكون شركتك أفضل\nمن الطريقة التي تظهر بها.', gapText: 'حين تتطور الشركة وتبقى العلامة والموقع والتواصل في مكانها، يصبح شرح القيمة أصعب من تقديمها.', belief: 'نفكّر قبل أن نصنع.', beliefText: 'لا نبدأ بلون أو شاشة أو منشور. نبدأ بما تغيّر في عملك وما الذي يجب أن يفهمه الناس بوضوح.', connect: 'علامة واحدة.\nتجربة واحدة.\nحضور واحد.', motion: 'مُقرن مفيدة عندما تكون الشركة في حركة.', cta: 'ما الذي يحتاج\nإلى أن يتغيــــــــر؟' },
    services: { title: 'ثلاث قدرات.\nشريك إبداعي واحد.', lead: 'اختر ما تحتاجه الآن، أو ابنِ نظاماً متصلاً يعمل عبر كل نقطة اتصال.' }, approach: { title: 'نفهم قبل\nأن نصنع.', lead: 'لا نبدأ بالمخرجات. نحدد ما الذي تغيّر، وما الذي يحتاج السوق إلى فهمه، ثم نبني التدخل الصحيح.' },
    thinking: { title: 'نفكر بصوت واضح.', lead: 'دراسات مستقلة وتجارب مفاهيمية تشرح كيف نرى فجوات الإدراك قبل أن نحلها.' },
    about: { title: 'صغيرة بما يكفي\nلتبقى قريبة.\nحادة بما يكفي\nلتصنع فرقاً.', lead: 'نحن لسنا شبكة كبيرة ولا فريق إنتاج بالقطعة. نعمل مباشرة مع الأعمال الطموحة عندما يصبح حضورها أقل من حقيقتها.' },
    contact: { title: 'لنبدأ بالسؤال\nالصحيح.', lead: 'أخبرنا بما تغيّر في عملك وما الذي تحتاج أن يراه السوق بشكل مختلف.' },
    nav: ['الرئيسية','الخدمات','التفكير','عن مُقرن','تواصل'], cta: 'ابدأ مشروعاً', study: 'دراسة مستقلة', studyTitle: 'تدقيق الإدراك الرقمي', studyText: 'استكشاف خارج-إلى-داخل لكيف يمكن للتجربة الرقمية أن تعكس جودة العمل بصورة أدق. ليست دراسة عميل ولا تدّعي نتائج.', servicesList: [['العلامة','ما أنت عليه.','تموضع، هوية، ونظام بصري واضح.'],['الويب','كيف تظهر رقمياً.','مواقع وتجارب تجعل القيمة مفهومة فوراً.'],['التواصل','كيف تتحدث إلى السوق.','فكرة، توجيه فني، وأصول إطلاق مؤثرة.']], triggers: ['تتوسع أسرع من صورتك الحالية','تطلق شيئاً مهماً','تدخل سوقاً جديداً','تستبدل حضوراً قديماً أو مربكاً'], principles: ['العمل قبل الزينة','الأنظمة قبل العناصر المنفصلة','الوضوح قبل التعقيد','الجودة قبل الحجم'] },
  en: {
    home: { hero: 'MAKE PERCEPTION\nCATCH UP WITH REALITY.', lead: 'Mugran is an independent creative company that builds the brand, shapes the digital experience, and brings it to market.', gap: 'YOUR BUSINESS MAY BE BETTER\nTHAN THE WAY IT APPEARS.', gapText: 'When the business moves while its brand, website and communication stand still, explaining value becomes harder than delivering it.', belief: 'WE THINK BEFORE WE MAKE.', beliefText: 'We do not begin with a colour, a screen or a post. We begin with what changed in the business and what people need to understand clearly.', connect: 'ONE BRAND.\nONE EXPERIENCE.\nONE PRESENCE.', motion: 'MUGRAN IS USEFUL WHEN A BUSINESS IS IN MOTION.', cta: 'WHAT NEEDS\nTO CHANGE?' },
    services: { title: 'THREE CAPABILITIES.\nONE CREATIVE PARTNER.', lead: 'Start with what you need now, or build a connected system across every touchpoint.' }, approach: { title: 'UNDERSTAND\nBEFORE WE MAKE.', lead: 'We do not begin with deliverables. We define what changed and what the market needs to understand, then build the right intervention.' },
    thinking: { title: 'WE SHOW THE THINKING.', lead: 'Independent studies and conceptual explorations for seeing a perception gap before solving it.' },
    about: { title: 'SMALL ENOUGH\nTO STAY CLOSE.\nSHARP ENOUGH\nTO MOVE THE NEEDLE.', lead: 'Not a large network and not a production line. We work directly with ambitious businesses when their presence falls behind their reality.' },
    contact: { title: 'START WITH\nTHE RIGHT QUESTION.', lead: 'Tell us what changed in the business and what the market needs to see differently.' },
    nav: ['HOME','SERVICES','THINKING','ABOUT','CONTACT'], cta: 'START A PROJECT', study: 'INDEPENDENT STUDY', studyTitle: 'DIGITAL PERCEPTION AUDIT', studyText: 'An outside-in exploration of how a digital experience can reflect the quality of a business more accurately. It is not client work and makes no outcome claim.', servicesList: [['BRAND','What you are.','Positioning, identity and a clear visual system.'],['WEB','How you show up digitally.','Websites and experiences that clarify value instantly.'],['CREATIVE','How you speak to the market.','The idea, art direction and launch assets that land.']], triggers: ['Growing beyond your current presentation','Launching something important','Entering a new market','Replacing an outdated or confusing presence'], principles: ['Business before decoration','Systems before isolated assets','Clarity before complexity','Quality over volume'] }
};

const paths=['/','/services','/work','/about','/contact'];
const powerServiceIcon='https://www.figma.com/api/mcp/asset/41c7abe2-de9c-4140-99da-5a802de282cf.svg';
const A=()=> null;

export default function MugranStudio({ page='home' }) {
  const { lang='ar', isRTL=true, openProjectModal }=useLanguage(); const t=copy[lang]||copy.ar; const d=t[page]||t.home;
  const root=useRef(null), scroller=useRef(null); const [open,setOpen]=useState(0);
  useEffect(()=>{const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced)return;const ctx=gsap.context(()=>{const hero=gsap.timeline({defaults:{ease:'power4.out'}});hero.from('.ms-hero .ms-kicker',{clipPath:isRTL?'inset(0 0 0 100%)':'inset(0 100% 0 0)',duration:.45}).from('.ms-hero h1',{clipPath:'inset(0 0 100% 0)',duration:.8},'-=.1').from('.ms-hero-film',{clipPath:isRTL?'inset(0 100% 0 0)':'inset(0 0 0 100%)',scale:.97,duration:.75},'-=.55').from('.ms-hero-bottom',{opacity:0,y:18,duration:.42},'-=.2');gsap.utils.toArray('[data-rise]').forEach(el=>gsap.from(el,{y:24,opacity:0,duration:.65,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 82%',once:true}}));if(scroller.current){gsap.to(scroller.current,{xPercent:isRTL?15:-15,ease:'none',scrollTrigger:{trigger:scroller.current.parentElement,start:'top bottom',end:'bottom top',scrub:true}})}},root);return()=>ctx.revert()},[lang,isRTL,page]);
  useEffect(()=>{const ctx=gsap.context(()=>{const reveal=(selector,vars)=>gsap.utils.toArray(selector).forEach((element,index)=>gsap.from(element,{...vars,delay:index*.06,scrollTrigger:{trigger:element,start:'top 86%',once:true}}));if(page==='services')reveal('.ms-services-detail article',{x:isRTL?64:-64,opacity:0,duration:.9,ease:'power3.out'});if(page==='work')reveal('.ms-study-list article',{y:70,rotate:isRTL?-2:2,opacity:0,duration:1,ease:'power3.out'});if(page==='about')reveal('.ms-principles div',{clipPath:'inset(0 100% 0 0)',duration:.9,ease:'power4.out'});if(page==='contact')gsap.from('.ms-contact',{scale:.94,y:44,opacity:0,duration:1,ease:'power3.out',scrollTrigger:{trigger:'.ms-contact',start:'top 80%',once:true}});if(page==='home'){const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;const desktop=window.matchMedia('(min-width: 901px)').matches;if(!reduce&&desktop){const timeline=gsap.timeline({defaults:{ease:'none'},scrollTrigger:{trigger:'.ms-gap',start:'top 74%',end:'bottom 42%',scrub:.65}});timeline.fromTo('.ms-gap-visual',{clipPath:isRTL?'inset(0 12% 0 0)':'inset(0 0 0 12%)',scale:1.06},{clipPath:'inset(0 0% 0 0)',scale:1,duration:1},0).fromTo('.ms-gap-reality',{xPercent:isRTL?-36:36},{xPercent:0,duration:1},0).fromTo('.ms-gap-perception',{xPercent:isRTL?36:-36},{xPercent:0,duration:1},0).fromTo('.ms-gap-marker',{scaleX:.25},{scaleX:1,duration:1},0).fromTo('.ms-gap-resolution',{opacity:0,y:8},{opacity:1,y:0,duration:.32},.72)}else{gsap.from('.ms-gap-visual',{clipPath:'inset(0 8% 0 8%)',scale:1.03,duration:.7,ease:'power3.out',scrollTrigger:{trigger:'.ms-gap',start:'top 82%',once:true}})}gsap.from('.ms-study-media',{clipPath:'inset(0 18% 0 18%)',scale:.92,scrollTrigger:{trigger:'.ms-study',start:'top 75%',end:'top 36%',scrub:true}})}},root);return()=>ctx.revert()},[page,isRTL]);
  const href=(i)=> isRTL ? (paths[i]==='/'?'/ar':'/ar'+paths[i]) : paths[i];
  const button=<button className="ms-button" onClick={()=>openProjectModal()}>{t.cta}<A/></button>;
  return <div ref={root} dir={isRTL?'rtl':'ltr'} className="ms-site">
    <section className={'ms-hero ms-'+page}><Grainient className="ms-hero-grain" color1="#000000" color2="#2A4A9F" color3="#000000" timeSpeed={0.55} warpStrength={0.55} warpFrequency={2.3} grainAmount={0.1} gamma={0.7}/><div className="ms-hero-film"><video autoPlay muted playsInline loop preload="metadata" poster="/image.png"><source src="/draft 2 done.mp4" type="video/mp4"/></video><button className="ms-hero-film-expand" type="button" aria-label={isRTL?'عرض الفيديو بكامل الشاشة':'Watch video fullscreen'} onClick={(event)=>{const video=event.currentTarget.parentElement.querySelector('video');if(video?.requestFullscreen)video.requestFullscreen();}}><img src="/icons/arrow-expand.svg" alt=""/></button></div><div className="ms-hero-wash"/><div className="ms-grid"><h1 data-reveal>{d.title||d.hero}</h1><div data-reveal className="ms-hero-bottom"><p>{d.lead}</p><button className="ms-button ms-hero-cta" onClick={()=>openProjectModal()}>{t.cta}</button></div></div></section>
    {page==='home' && <Home t={t} isRTL={isRTL} open={open} setOpen={setOpen} scroller={scroller} button={button}/>} 
    {page==='services' && <Services t={t} open={open} setOpen={setOpen} button={button}/>} 
    {page==='work' && <Thinking t={t} button={button}/>} 
    {page==='approach' && <Approach t={t} button={button}/>} 
    {page==='about' && <About t={t} button={button}/>} 
    {page==='contact' && <Contact t={t} button={button}/>} 
    <nav className="ms-footer-nav">{t.nav.map((x,i)=><Link key={x} href={href(i)}>{x}</Link>)}</nav>
  </div>;
}

function ServiceIndex({t,isRTL,open,setOpen}){const ref=useRef(null),cursor=useRef(null);const [fine,setFine]=useState(false);useEffect(()=>{const query=window.matchMedia('(pointer:fine)');const update=()=>setFine(query.matches);update();query.addEventListener?.('change',update);return()=>query.removeEventListener?.('change',update)},[]);useEffect(()=>{if(!fine||!cursor.current)return;const moveX=gsap.quickTo(cursor.current,'x',{duration:.42,ease:'power3.out'}),moveY=gsap.quickTo(cursor.current,'y',{duration:.42,ease:'power3.out'});const move=event=>{const box=ref.current.getBoundingClientRect();moveX(event.clientX-box.left-55);moveY(event.clientY-box.top-55)};const element=ref.current;element.addEventListener('pointermove',move);return()=>element.removeEventListener('pointermove',move)},[fine]);const tags=isRTL?[['استراتيجية','هوية','أنظمة'],['UX/UI','مواقع','تجارب رقمية'],['حملات','توجيه فني','إطلاق']]:[['Strategy','Identity','Systems'],['UX/UI','Websites','Digital Experiences'],['Campaigns','Art Direction','Launch']];const graphics=['/pen-tool-03.svg','/cursor-edit-02.svg','/stars.svg'];return <div ref={ref} className={`ms-service-index ${fine?'has-pointer':''}`}><div ref={cursor} className="ms-service-explore">{isRTL?'استكشف ↗':'EXPLORE ↗'}</div>{t.servicesList.map((service,index)=><button key={service[0]} type="button" className={`ms-service-row ${open===index?'active':''}`} onMouseEnter={()=>setOpen(index)} onFocus={()=>setOpen(index)} onClick={()=>setOpen(index)}><span className="ms-service-number">0{index+1}</span><span className="ms-service-name">{service[0]}</span><em>{service[1]}</em><span className="ms-service-tags">{tags[index].map(tag=><span key={tag}>{tag}</span>)}</span><img src={graphics[index]} alt=""/><span className="ms-service-arrow" aria-hidden="true">↗</span></button>)}</div>}

function Home({t,isRTL,open,setOpen,scroller,button}){const gap=isRTL?{eyebrow:'فجوة الإدراك',title:'عملك قد يكون\nأقوى مما يظهــــــر.',copy:'حين تتقدم قدرات الشركة على الطريقة التي تظهر بها،\nتنشأ فجوة بين حقيقتها وكيف يراها السوق.',payoff:'هنا نُغلق فجوة الإدراك.',reality:'حقيقة الشركة',realityDetail:'خبرة · نمو · جودة · ثقة',perception:'ما يراه السوق',perceptionDetail:'علامة · موقع · تواصل · تجربة'}:{eyebrow:'THE PERCEPTION GAP',title:'Your business can outgrow\nthe way it appears.',copy:'When capability moves faster than brand, website and communication, value becomes harder to see.',payoff:'MAKE PERCEPTION CATCH UP WITH REALITY.',reality:'BUSINESS REALITY',realityDetail:'Capability · Growth · Quality · Trust',perception:'MARKET PERCEPTION',perceptionDetail:'Brand · Website · Communication · Experience'};return <>
  <section className="ms-gap ms-grid"><div className="ms-gap-copy"><p className="ms-kicker">{gap.eyebrow}</p><h2>{gap.title}</h2><p>{gap.copy}</p><p className="ms-gap-payoff">{gap.payoff}</p></div><div className="ms-gap-stage"><aside className="ms-gap-fact ms-gap-reality"><span>{gap.reality}</span><p>{gap.realityDetail}</p></aside><div className="ms-gap-visual" aria-label={gap.eyebrow}><video autoPlay muted playsInline loop preload="metadata"><source src="/0_Abstract_Technology_1280x720.mp4" type="video/mp4"/></video></div><aside className="ms-gap-fact ms-gap-perception"><span>{gap.perception}</span><p>{gap.perceptionDetail}</p></aside></div></section>
  <section className="ms-manifesto"><div className="ms-grid"><h2 data-rise>{t.home.belief}</h2><p data-rise>{t.home.beliefText}</p></div></section>
  <section className="ms-services"><div className="ms-grid"><p className="ms-kicker">{isRTL?'ما نبنيه':'WHAT WE BUILD'}</p><ServiceIndex t={t} isRTL={isRTL} open={open} setOpen={setOpen}/></div></section>
  <section className="ms-connect"><div className="ms-rail" ref={scroller}>{t.home.connect}</div></section>
  <section className="ms-motion"><div className="ms-grid"><h2 data-rise>{t.home.motion}</h2><ul>{t.triggers.map(x=><li data-rise key={x}>{x}<A/></li>)}</ul></div></section>
  <section className="ms-final ms-grid"><h2 data-rise>{t.home.cta}</h2><div data-rise>{button}</div></section>
</>}
function Services({t,open,setOpen,button}){const ar=t.nav[0]==='الرئيسية';const base=ar?'/ar/services':'/en/services';const routes=['brand','web','creative'];return <main className="ms-page ms-grid"><section className="ms-services-detail">{t.servicesList.map((s,i)=><Link data-rise key={s[0]} href={`${base}/${routes[i]}`} onMouseEnter={()=>setOpen(i)} className={open===i?'active':''}><article><span>0{i+1}</span><h2>{s[0]}</h2><em>{s[1]}</em><p>{s[2]}</p><div>{i===0?'Identity · Positioning · Systems':i===1?'Corporate websites · Digital experiences · UX/UI':'Campaign concepts · Art direction · Launch assets'} <img className="ms-inline-arrow" src="/icons/arrow-up-right-01.svg" alt=""/></div></article></Link>)}</section><section className="ms-services-relationship" data-rise><p>{ar?'أحياناً تعبر المشكلة القدرات الثلاث.':'SOMETIMES THE PROBLEM CROSSES ALL THREE.'}</p><div>{t.servicesList.map(s=><span key={s[0]}><b>{s[0]}</b><em>{s[1]}</em></span>)}</div></section><section className="ms-partner" data-rise><p className="ms-kicker">{ar?'لنبدأ بالمشكلة':'START WITH THE PROBLEM'}</p><h2>{ar?'ما الذي يحتاج\nأن يتغيــــــــر؟':'WHAT NEEDS\nTO CHANGE?'}</h2>{button}</section></main>}
function Thinking({t,button}){return <main className="ms-page ms-grid"><section className="ms-study-list"><article data-rise><p className="ms-kicker">{t.study}</p><h2>{t.studyTitle}</h2><p>{t.studyText}</p><div className="ms-study-image"/></article><article data-rise><p className="ms-kicker">{t.nav[0]==='الرئيسية'?'تجربة مفاهيمية':'CONCEPT EXPLORATION'}</p><h2>{t.nav[0]==='الرئيسية'?'الحرفية العربية\nما بعد الترجمة':'ARABIC DIGITAL CRAFT\nBEYOND TRANSLATION'}</h2><p>{t.nav[0]==='الرئيسية'?'كيف تُبنى التجربة العربية من اتجاه القراءة، والإيقاع، وشكل الحروف، لا من قلب واجهة إنجليزية.':'How bilingual experience is built from reading direction, rhythm and letterforms, not from flipping an English interface.'}</p></article></section><section data-rise className="ms-thinking-cta"><h2>{t.nav[0]==='الرئيسية'?'هل لديك فجوة تحتاج إلى اسم؟':'DO YOU HAVE A GAP\nTHAT NEEDS A NAME?'}</h2>{button}</section></main>}
function Approach({t,button}){const ar=t.nav[0]==='الرئيسية';const steps=ar?[['افهم','ما الذي تغيّر في العمل؟'],['عرّف','ما الذي يجب أن يفهمه السوق؟'],['اختصر','الفكرة في نظام واضح.'],['ابنِ','العلامة والتجربة والمادة.'],['فعّل','الحضور في النقطة المناسبة.']]:[['UNDERSTAND','What changed in the business?'],['DEFINE','What must the market understand?'],['DISTILL','Turn the idea into a clear system.'],['BUILD','The brand, experience and material.'],['ACTIVATE','Bring it to the right touchpoint.']];return <main className="ms-page ms-grid"><section className="ms-approach-intro" data-rise><p className="ms-kicker">{ar?'المنهج':'THE APPROACH'}</p><p>{ar?'لا نصف خدمة قبل أن نفهم الفجوة. هذا يحافظ على القرار واضحاً، وعلى العمل متصلاً بما يحتاجه العمل فعلاً.':'We do not prescribe a service before we understand the gap. It keeps the decision clear and the work connected to what the business actually needs.'}</p></section><section className="ms-approach-steps">{steps.map(([name,detail],index)=><article data-rise key={name}><span>0{index+1}</span><h2>{name}</h2><p>{detail}</p></article>)}</section><section className="ms-approach-close" data-rise><h2>{ar?'قرار واضح.\nتنفيذ متصل.':'A CLEAR DECISION.\nA CONNECTED BUILD.'}</h2>{button}</section></main>}
function About({t,button}){return <main className="ms-page ms-grid"><section className="ms-about-copy" data-rise><p>{t.about.lead}</p><h2>{t.nav[0]==='الرئيسية'?'شركة إبداعية مستقلة\nتعمل معك مباشرة.':'AN INDEPENDENT CREATIVE COMPANY\nTHAT WORKS DIRECTLY WITH YOU.'}</h2></section><section className="ms-principles">{t.principles.map(x=><div data-rise key={x}>{x}</div>)}</section><section data-rise className="ms-about-end"><p>{t.nav[0]==='الرئيسية'?'لا نعد بأن نكون كل شيء. نركز على أن نكون الشريك الصحيح عندما تصبح صورة الشركة أقل من حقيقتها.':'We do not promise to be everything. We focus on being the right partner when a company’s presence falls behind its reality.'}</p>{button}</section></main>}
function Contact({t}){
  const isArabic=t.nav[0]==='الرئيسية';
  const [sent,setSent]=useState(false);
  const submit=(event)=>{
    event.preventDefault();
    const form=new FormData(event.currentTarget);
    const subject=isArabic?'استفسار مشروع جديد عبر موقع مُقرن':'New project enquiry via Mugran website';
    const message=isArabic
      ? `الاسم والشركة: ${form.get('name')}\nالبريد: ${form.get('email')}\nالهاتف: ${form.get('phone') || 'غير مذكور'}\n\nالمطلوب: ${form.get('scope')}\n\nما الذي يحتاج إلى أن يتغير؟\n${form.get('message')}`
      : `Name and company: ${form.get('name')}\nEmail: ${form.get('email')}\nPhone: ${form.get('phone') || 'Not provided'}\n\nProject focus: ${form.get('scope')}\n\nWhat needs to change?\n${form.get('message')}`;
    window.location.href=`mailto:info@mugranagency.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(message)}`;
    setSent(true);
  };
  return <main className="ms-page ms-grid"><section data-rise className="ms-contact"><div><p className="ms-kicker">{t.nav[4]}</p><h2>{t.contact.title}</h2><p>{t.contact.lead}</p><a className="ms-contact-email" href="mailto:info@mugranagency.com">info@mugranagency.com</a></div><form onSubmit={submit}><label>{isArabic?'الاسم والشركة':'NAME + COMPANY'}<input name="name" required autoComplete="name"/></label><label>{isArabic?'البريد الإلكتروني':'EMAIL'}<input name="email" type="email" required autoComplete="email"/></label><label>{isArabic?'رقم الهاتف (اختياري)':'PHONE (OPTIONAL)'}<input name="phone" type="tel" autoComplete="tel"/></label><label>{isArabic?'كيف يمكن أن نساعد؟':'HOW CAN WE HELP?'}<select name="scope" defaultValue=""><option value="" disabled>{isArabic?'اختر مجالاً':'SELECT A FOCUS'}</option><option>{isArabic?'العلامة والتموضع':'Brand and positioning'}</option><option>{isArabic?'موقع أو تجربة رقمية':'Website or digital experience'}</option><option>{isArabic?'حملة أو توجيه إبداعي':'Campaign or creative direction'}</option><option>{isArabic?'لست متأكداً بعد':'Not sure yet'}</option></select></label><label>{isArabic?'ما الذي يحتاج إلى أن يتغير؟':'WHAT NEEDS TO CHANGE?'}<textarea name="message" rows="4" required placeholder={isArabic?'جملة أو فقرة قصيرة تكفي.':'A short paragraph is enough.'}/></label><button className="ms-button" type="submit">{isArabic?'إرسال الملخص':'SEND THE BRIEF'}<A/></button>{sent&&<p className="ms-form-note">{isArabic?'فُتحت رسالة جاهزة في بريدك لإرسالها إلى مُقرن.':'A ready-to-send email has opened for you.'}</p>}</form></section></main>
}
