'use client';

import { useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useLanguage } from '../context/LanguageContext';

export default function Navbar() {
  const { lang = 'ar', isRTL = true, toggleLang, openProjectModal } = useLanguage();
  const path = usePathname() || '/';
  const [scrolled, setScrolled] = useState(false), [menuOpen, setMenuOpen] = useState(false), [servicesOpen, setServicesOpen] = useState(false);
  const servicesRef = useRef(null);
  const base = isRTL ? '/ar' : '/en';
  const nav = isRTL ? [['عن مُقرن', '/about'], ['المنهج', '/approach'], ['تواصل', '/contact']] : [['ABOUT', '/about'], ['APPROACH', '/approach'], ['CONTACT', '/contact']];
  const services = isRTL ? [['العلامة', 'هوية واستراتيجية تجعل قيمة الشركة أوضح.', '/brand'], ['الويب', 'مواقع وتجارب رقمية تعكس مستوى العمل.', '/web'], ['الإبداع', 'أفكار وحملات ومحتوى يقدّم العلامة للسوق.', '/creative']] : [['BRAND', 'Strategy, identity and visual systems.', '/brand'], ['WEB', 'Websites and digital experiences.', '/web'], ['CREATIVE', 'Campaigns, art direction and creative communication.', '/creative']];
  const servicesActive = path.startsWith(`${base}/services`);

  useEffect(() => { const watch = () => setScrolled(window.scrollY > 24); watch(); window.addEventListener('scroll', watch, { passive: true }); return () => window.removeEventListener('scroll', watch); }, []);
  useEffect(() => { const close = event => { if (event.key === 'Escape') setServicesOpen(false); if (event.type === 'pointerdown' && servicesRef.current && !servicesRef.current.contains(event.target)) setServicesOpen(false); }; document.addEventListener('keydown', close); document.addEventListener('pointerdown', close); return () => { document.removeEventListener('keydown', close); document.removeEventListener('pointerdown', close); }; }, []);
  useEffect(() => { setServicesOpen(false); setMenuOpen(false); }, [path]);
  const logo = isRTL ? '/arlogo.svg' : '/H Logo.svg';

  return <header className={`agency-nav ${scrolled ? 'is-scrolled' : ''}`} dir={isRTL ? 'rtl' : 'ltr'}>
    <div className="mugran-grid-container agency-nav-inner">
      <Link href={base} className="agency-logo" aria-label="Mugran home"><Image src={logo} alt="Mugran" width={164} height={48} priority /></Link>
      <nav aria-label={isRTL ? 'التنقل الرئيسي' : 'Primary navigation'}>
        {nav.slice(0, 1).map(([label, href]) => <Link className="nav-link" aria-current={path === `${base}${href}` ? 'page' : undefined} data-active={path === `${base}${href}` || undefined} key={href} href={`${base}${href}`}>{label}</Link>)}
        <div className="services-nav" ref={servicesRef} onMouseEnter={() => setServicesOpen(true)} onMouseLeave={() => setServicesOpen(false)}>
          <Link className="nav-link services-link" data-active={servicesActive || undefined} href={`${base}/services`}>{isRTL ? 'الخدمات' : 'SERVICES'}</Link>
          <button type="button" className="services-toggle" aria-label={isRTL ? 'فتح قائمة الخدمات' : 'Open services menu'} aria-expanded={servicesOpen} onClick={() => setServicesOpen(!servicesOpen)}><img src="/icons/arrow-down-01.svg" alt=""/></button>
          {servicesOpen && <div className="services-dropdown">{services.map(([name, description, href]) => <Link href={`${base}/services${href}`} key={href}><b>{name}</b><span>{description}</span></Link>)}<Link className="all-services" href={`${base}/services`}>{isRTL ? 'عرض جميع الخدمات' : 'VIEW ALL SERVICES'} <img src="/icons/arrow-up-right-01.svg" alt=""/></Link></div>}
        </div>
        {nav.slice(1).map(([label, href]) => <Link className="nav-link" aria-current={path === `${base}${href}` ? 'page' : undefined} data-active={path === `${base}${href}` || undefined} key={href} href={`${base}${href}`}>{label}</Link>)}
      </nav>
      <div className="nav-actions"><button className="language" type="button" onClick={toggleLang}>{lang === 'ar' ? 'EN' : 'ع'}</button><button className="nav-project" type="button" onClick={openProjectModal}><span>{isRTL ? 'ابدأ مشروعك' : 'START A PROJECT'}</span><img src="/icons/arrow-up-right-01.svg" alt=""/></button><button className="mobile-menu" type="button" aria-label={menuOpen ? 'Close menu' : 'Open menu'} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? '×' : '☰'}</button></div>
    </div>
    {menuOpen && <div className="agency-drawer">{nav.slice(0,1).map(([label, href]) => <Link className="drawer-link" key={href} href={`${base}${href}`}>{label}</Link>)}<button type="button" className="drawer-services" onClick={() => setServicesOpen(!servicesOpen)}>{isRTL ? 'الخدمات' : 'SERVICES'} <span>{servicesOpen ? '−' : '+'}</span></button>{servicesOpen && <div className="drawer-submenu">{services.map(([name,, href]) => <Link key={href} href={`${base}/services${href}`}>{name}</Link>)}</div>}{nav.slice(1).map(([label, href]) => <Link className="drawer-link" key={href} href={`${base}${href}`}>{label}</Link>)}</div>}
    <style jsx>{`
      .agency-nav{position:fixed;inset:0 0 auto;z-index:100;padding:26px 0;background:rgba(12,13,15,.82);border-bottom:1px solid rgba(255,255,255,.1);transition:padding .35s ease,background .35s ease}.agency-nav.is-scrolled{padding:13px 0;background:rgba(12,13,15,.94);backdrop-filter:blur(14px);border-bottom:1px solid rgba(255,255,255,.12)}.agency-nav-inner{display:flex;align-items:center;justify-content:space-between}.agency-logo{display:flex;width:164px;height:48px}.agency-logo :global(img){width:164px;height:48px;object-fit:contain;object-position:left center;filter:brightness(0) invert(1)}
      .agency-nav nav{display:flex;align-items:center;gap:18px}.nav-link,.language{font:700 11px var(--font-mono);letter-spacing:.08em;color:#f9fdff!important}.nav-link{display:inline-flex;align-items:center;min-height:44px;padding:0 7px;transition:color .24s ease,transform .24s ease}.nav-link:hover,.nav-link:focus-visible,.nav-link[data-active]{color:#6d8ef0!important}.nav-link:hover{transform:translateY(-1px)}.services-nav{position:relative;display:flex;align-items:center}.services-link{padding-inline-end:2px}.services-toggle{display:grid;place-items:center;min-width:32px;min-height:44px}.services-toggle img{width:13px;height:13px;filter:brightness(0) invert(1);transition:filter .24s,transform .24s}.services-toggle[aria-expanded="true"] img{transform:rotate(180deg)}.services-toggle:hover img,.services-toggle:focus-visible img{filter:invert(55%) sepia(59%) saturate(610%) hue-rotate(191deg)}.services-dropdown{position:absolute;top:44px;inset-inline-start:0;width:300px;padding:12px;background:#121419;border:1px solid #454a55;box-shadow:0 20px 48px rgba(0,0,0,.3);animation:dropdown-in .2s ease-out both}.services-dropdown>a{display:block;padding:14px;color:#e9e8e3;transition:background .2s,color .2s}.services-dropdown>a:hover,.services-dropdown>a:focus-visible{background:#1b2440;color:#fff}.services-dropdown b,.services-dropdown span{display:block}.services-dropdown b{font:700 11px var(--font-mono);letter-spacing:.08em}.services-dropdown span{margin-top:6px;color:#adb0b8;font-size:12px;line-height:1.4}.services-dropdown .all-services{display:flex;align-items:center;gap:8px;margin-top:6px;padding-top:16px;border-top:1px solid #30333a;color:#87a3ff;font:700 10px var(--font-mono);letter-spacing:.07em}.all-services img{width:13px;height:13px;filter:invert(62%) sepia(34%) saturate(704%) hue-rotate(184deg)}@keyframes dropdown-in{from{opacity:0;transform:translateY(7px)}to{opacity:1;transform:none}}
      .nav-actions{display:flex;align-items:center;gap:13px}.language{min-width:44px;min-height:44px;padding:8px;transition:color .24s}.language:hover{color:#a8bdff}.nav-project{display:flex;gap:9px;align-items:center;min-height:44px;background:#f9fdff;color:#101114;font-size:12px;font-weight:800;padding:11px 15px;border-radius:3px;transition:background .25s,transform .18s}.nav-project:hover{background:#dce7ff}.nav-project img{width:15px;height:15px;transition:transform .25s}.nav-project:hover img{transform:translate(3px,-3px)}.nav-project:active{transform:scale(.985)}.nav-link:focus-visible,.services-toggle:focus-visible,.language:focus-visible,.nav-project:focus-visible,.mobile-menu:focus-visible,.services-dropdown a:focus-visible{outline:2px solid #a8bdff;outline-offset:3px}.mobile-menu{display:none;min-width:44px;min-height:44px;font-size:24px;color:#f9fdff}.agency-drawer{display:none}
      @media(max-width:780px){.agency-nav{padding:18px 0}.agency-nav nav,.nav-project{display:none}.mobile-menu{display:block}.agency-drawer{display:flex;position:absolute;top:72px;inset-inline:18px;flex-direction:column;background:#101114;padding:14px 18px 20px;border:1px solid #30333a}.drawer-link,.drawer-services,.drawer-submenu a{min-height:44px;display:flex;align-items:center;color:#f9fdff;font-size:16px;font-weight:700;text-align:start}.drawer-services{justify-content:space-between}.drawer-submenu{padding-inline-start:18px;border-inline-start:1px solid #2A4A9F}.drawer-submenu a{color:#bfc7da;font-size:14px}.agency-logo,.agency-logo :global(img){width:118px;height:36px}}
    `}</style>
  </header>;
}
