'use client';
import { useEffect, useRef } from 'react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { useLanguage } from '../context/LanguageContext';
import './ServiceDetail.css';
if(typeof window!=='undefined')gsap.registerPlugin(ScrollTrigger);
const content={brand:{en:{hero:"THE PROBLEM ISN'T\nALWAYS THE LOGO.",lead:'A business can grow while its identity, positioning and communication remain behind.',cap:['Brand Strategy','Positioning','Visual Identity','Brand Systems','Guidelines','Company Profiles','Presentation Systems'],when:['Entering a new market','The company has outgrown its identity','Launching something important','The brand feels inconsistent','Business quality is stronger than its presentation'],cta:'DISCUSS YOUR BRAND'},ar:{hero:'ليست المشكلة دائماً\nفي الشعار.',lead:'قد يتطور العمل بينما تبقى هويته وتموضعه وطريقة تواصله خلف ما أصبح عليه.',cap:['استراتيجية العلامة','التموضع','الهوية البصرية','أنظمة العلامة','الإرشادات','ملفات الشركات','أنظمة العروض'],when:['دخول سوق جديد','تجاوز الهوية الحالية','إطلاق شيء مهم','عدم اتساق العلامة','جودة العمل أقوى من صورته'],cta:'ناقش علامتك'}},web:{en:{hero:'YOUR WEBSITE IS\nPART OF THE BUSINESS.',lead:'It should make the company easier to understand, trust and act on.',cap:['Corporate Websites','Business Websites','Landing Pages','UX/UI Design','Digital Experiences','Web Development','Product / SaaS UI'],when:['Confusing positioning','Weak hierarchy','Outdated experience','Poor mobile UX','Low credibility','Unclear conversion path'],cta:'DISCUSS YOUR WEBSITE'},ar:{hero:'موقعك ليس مجرد\nمكان على الإنترنت.',lead:'هو جزء من العمل: يجعل الشركة أسهل للفهم، وأكثر جدارة بالثقة، وأسهل لاتخاذ الخطوة التالية معها.',cap:['مواقع الشركات','مواقع الأعمال','صفحات الهبوط','تصميم UX/UI','تجارب رقمية','تطوير الويب','واجهات المنتجات'],when:['تموضع مربك','تسلسل ضعيف','تجربة قديمة','تجربة موبايل ضعيفة','مصداقية منخفضة','مسار تحويل غير واضح'],cta:'ناقش موقعك'}},creative:{en:{hero:'A GOOD BRAND\nSTILL NEEDS TO BE SEEN.',lead:'Creative direction turns one clear brand into communication that arrives with coherence.',cap:['Campaign Concepts','Art Direction','Launch Campaigns','Social Creative','Content Direction','Creative Assets'],when:['A launch needs a clear point of view','Content has become random','The brand needs a new moment','Campaign activity lacks a shared direction'],cta:'DISCUSS YOUR CAMPAIGN'},ar:{hero:'العلامة لا يكفي\nأن تكون جيدة.\nيجب أن تُرى.',lead:'التوجيه الإبداعي يحوّل علامة واضحة إلى تواصل يصل إلى السوق باتساق ومعنى.',cap:['أفكار الحملات','التوجيه الفني','حملات الإطلاق','الإبداع الاجتماعي','توجيه المحتوى','الأصول الإبداعية'],when:['إطلاق يحتاج إلى وجهة نظر واضحة','المحتوى أصبح عشوائياً','العلامة تحتاج لحظة جديدة','النشاط بلا اتجاه مشترك'],cta:'ناقش حملتك'}}};
const Arrow=()=> <img className="service-arrow" src="/icons/arrow-up-right-01.svg" alt=""/>;
export default function ServiceDetail({type}){const {lang,isRTL,openProjectModal}=useLanguage();const t=content[type][lang];const root=useRef(null);useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const ctx=gsap.context(()=>{gsap.timeline().from('.service-detail-hero h1',{clipPath:'inset(0 0 100% 0)',duration:.75,ease:'power4.out'}).from('.service-detail-hero p',{y:18,opacity:0,duration:.45},'-.3');gsap.utils.toArray('.service-detail-reveal').forEach(el=>gsap.from(el,{y:28,opacity:0,duration:.65,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 83%',once:true}}))},root);return()=>ctx.revert()},[lang,type]);return <div ref={root} className="service-detail" dir={isRTL?'rtl':'ltr'}><section className="service-detail-hero service-detail-shell"><p>{type.toUpperCase()} / 0{['brand','web','creative'].indexOf(type)+1}</p><h1>{t.hero}</h1><div><span>{t.lead}</span><button onClick={openProjectModal}>{t.cta}<Arrow/></button></div></section><section className="service-detail-cap service-detail-shell service-detail-reveal"><p className="service-label">{isRTL?'ما نبنيه':'WHAT WE BUILD'}</p><ul>{t.cap.map((item,index)=><li key={item}><span>0{index+1}</span>{item}</li>)}</ul></section><section className="service-detail-when service-detail-shell service-detail-reveal"><div><p className="service-label">{isRTL?'متى تكون مفيدة':'WHEN THIS IS USEFUL'}</p><h2>{type==='creative'?(isRTL?'علامة واحدة.\nلحظات كثيرة.\nاتجاه واحد.':'ONE BRAND.\nMANY MOMENTS.\nONE DIRECTION.'):(isRTL?'حين تصبح صورتك\nأقل من حقيقتك.':'WHEN YOUR PRESENCE\nFALLS BEHIND REALITY.')}</h2></div><ul>{t.when.map(item=><li key={item}><Arrow/>{item}</li>)}</ul></section><section className="service-detail-end service-detail-shell service-detail-reveal"><button onClick={openProjectModal}>{t.cta}<Arrow/></button></section></div>}
